# Generated by Django 3.2.7 on 2021-09-07 03:00

from django.db import migrations, models
import django_summernote.utils


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20210907_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=django_summernote.utils.uploaded_filepath),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True),
        ),
    ]
