# Generated by Django 3.2.7 on 2021-09-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
