# Generated by Django 3.2.7 on 2021-09-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20210907_0300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Attachment',
        ),
    ]
