# Generated by Django 3.2.7 on 2021-09-05 22:17

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contactmessage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=django_quill.fields.QuillField(),
        ),
    ]
